# Generated by Django 4.2.4 on 2023-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle_number'], name='app_gpsdata_vehicle_6bf1f1_idx')],
            },
        ),
    ]
