# Generated by Django 4.2.4 on 2023-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_gpsdata_latitude_alter_gpsdata_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='gpsdata',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
