# Generated by Django 4.2.4 on 2023-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_gpsdata_latitude_alter_gpsdata_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_2',
            field=models.TextField(null=True),
        ),
    ]
