# Generated by Django 4.2.4 on 2023-08-23 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customer_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emergency_contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='pulses',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tyre_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
