# Generated by Django 4.2.4 on 2023-08-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_emergency_contacts_customer_pulses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
