# Generated by Django 4.2.4 on 2023-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tyre_size',
            field=models.FloatField(null=True),
        ),
    ]
