# Generated by Django 4.2.4 on 2023-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_datastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
