# Generated by Django 4.2.4 on 2023-08-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_datastore_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='address',
        ),
    ]
