# Generated by Django 4.2.4 on 2023-09-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_datastore_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStoreSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('police_station_contact', models.CharField(max_length=100, null=True)),
                ('ambulance_contact', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='app.datastoresegment'),
        ),
    ]
