# Generated by Django 4.2.4 on 2023-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_datastoresegment_datastore_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastoresegment',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
