# Generated by Django 4.2.4 on 2023-10-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_datastoresegment_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastoresegment',
            name='distance',
        ),
    ]
