# Generated by Django 4.2.4 on 2024-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_datastoresegment_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100)),
                ('tyre_size', models.FloatField(null=True)),
                ('pulses', models.FloatField(null=True)),
                ('device_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pulses',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tyre_size',
        ),
    ]
